# Generated by Django 4.1.3 on 2022-12-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Category_Image',
            field=models.ImageField(blank=True, null=True, upload_to='files/CategoryImages'),
        ),
    ]
