# Generated by Django 4.1.3 on 2022-12-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_category_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Price', models.FloatField(blank=True, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('ReStock_Level', models.IntegerField(blank=True, null=True)),
                ('main_Image', models.ImageField(blank=True, null=True, upload_to='files/ProductImages')),
                ('Image_One', models.ImageField(blank=True, null=True, upload_to='files/ProductImages')),
                ('Image_Two', models.ImageField(blank=True, null=True, upload_to='files/ProductImages')),
                ('Image_Three', models.ImageField(blank=True, null=True, upload_to='files/ProductImages')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Category', models.ManyToManyField(blank=True, default=None, related_name='product_Category', to='client.category')),
                ('Colors', models.ManyToManyField(blank=True, default=None, related_name='product_Colors', to='client.colours')),
                ('Sizes', models.ManyToManyField(blank=True, default=None, related_name='product_Sizes', to='client.itemsize')),
            ],
        ),
    ]
