# Generated by Django 4.1.3 on 2022-12-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_salecollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_display',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='salecollection',
            name='main_display',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
    ]
