# Generated by Django 4.1.3 on 2022-12-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_newarrivals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salecollection',
            name='main_display',
            field=models.CharField(choices=[('First', 'First'), ('second', 'second'), ('third', 'third')], default='No', max_length=10),
        ),
    ]
