# Generated by Django 4.1.3 on 2022-12-05 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_alter_blog_city_town_alter_blog_event_timeend_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size', models.CharField(blank=True, max_length=300, null=True)),
                ('Sub_Total', models.FloatField(blank=True, null=True)),
                ('satus', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('complete', 'complete')], default='pending', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('ProductKey', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cart_key', to='client.product')),
            ],
        ),
    ]
