# Generated by Django 4.1.3 on 2022-12-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
