# Generated by Django 4.1.3 on 2022-12-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_cartitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='sale_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
