# Generated by Django 4.1.3 on 2022-12-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_cartitems_sale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Option_Picked', models.CharField(blank=True, max_length=100, null=True)),
                ('Name', models.CharField(blank=True, max_length=300, null=True)),
                ('LastName', models.CharField(blank=True, max_length=300, null=True)),
                ('Contact', models.CharField(blank=True, max_length=300, null=True)),
                ('AltContact', models.CharField(blank=True, max_length=300, null=True)),
                ('Email', models.CharField(blank=True, max_length=300, null=True)),
                ('ComplexDetails', models.CharField(blank=True, max_length=300, null=True)),
                ('Street', models.CharField(blank=True, max_length=300, null=True)),
                ('Suburb', models.CharField(blank=True, max_length=300, null=True)),
                ('City', models.CharField(blank=True, max_length=300, null=True)),
                ('Province', models.CharField(blank=True, max_length=300, null=True)),
                ('PostalCode', models.CharField(blank=True, max_length=300, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Category', models.ManyToManyField(blank=True, default=None, related_name='user_cart', to='client.cartitems')),
            ],
        ),
    ]
