# Generated by Django 4.1.3 on 2022-12-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_deliveryoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoption',
            name='GrandTotal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
