# Generated by Django 4.1.3 on 2022-12-05 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_deliveryoption_grandtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryoption',
            old_name='Category',
            new_name='UserItems',
        ),
    ]
