# Generated by Django 4.1.3 on 2022-12-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_deliveryoption_object_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='satus',
            field=models.CharField(choices=[('cart', 'cart'), ('pending', 'pending'), ('paid', 'paid'), ('complete', 'complete')], default='cart', max_length=100),
        ),
    ]
