# Generated by Django 4.1.3 on 2022-12-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_laybyoptions_product_layby'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='End_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Sale_Price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_CoverImages',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_display',
            field=models.CharField(blank=True, choices=[('First', 'First'), ('second', 'second'), ('third', 'third')], default='No', max_length=10, null=True),
        ),
    ]
