# Generated by Django 4.1.3 on 2022-12-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0023_alter_product_main_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10, null=True),
        ),
    ]
