# Generated by Django 4.1.3 on 2022-12-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0024_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='arrivals_CoverImages',
            field=models.CharField(blank=True, choices=[('First', 'First'), ('second', 'second'), ('third', 'third')], default='No', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10, null=True),
        ),
    ]
