# Generated by Django 4.1.3 on 2022-12-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0025_product_arrivals_coverimages_product_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoption',
            name='customer_ref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
