# Generated by Django 4.1.3 on 2022-12-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0027_paxipackages'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoption',
            name='addressLine1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='addressLine2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='addressLine3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='addressLine4',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='addressLine5',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='addressLine6',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='addressLine7',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='paxiPackageId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
