# Generated by Django 4.1.3 on 2022-12-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0028_deliveryoption_addressline1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoption',
            name='deliveryFee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
