# Generated by Django 4.1.3 on 2022-12-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0029_deliveryoption_deliveryfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoption',
            name='AmountDue',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
