# Generated by Django 4.1.3 on 2022-12-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0031_customermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='formComplete',
            field=models.CharField(blank=True, default='Yes', max_length=100, null=True),
        ),
    ]
