# Generated by Django 4.1.3 on 2022-12-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0032_customermodel_formcomplete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='formComplete',
            field=models.CharField(blank=True, default='No', max_length=100, null=True),
        ),
    ]
