# Generated by Django 4.1.3 on 2022-12-16 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0033_alter_customermodel_formcomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='CustomerId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_cart', to='client.customermodel'),
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='CustomerId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to='client.customermodel'),
        ),
    ]
