# Generated by Django 4.1.3 on 2022-12-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0034_cartitems_customerid_deliveryoption_customerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryoption',
            name='CustomerId',
        ),
    ]
