# Generated by Django 4.1.3 on 2022-12-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0036_deliveryoption_customerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoption',
            name='order_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
