# Generated by Django 4.1.3 on 2022-12-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0037_deliveryoption_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewLetterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
